import esbuild from 'esbuild';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

async function build() {
	try {
		await esbuild.build({
			banner: {
				js: banner,
			},
			entryPoints: ['src/main.ts'],
			bundle: true,
			external: [
				'obsidian',
				'electron',
				'sortablejs',
				'node:module',
				...builtinModules,
			],
			format: 'cjs',
			target: 'es2017',
			logLevel: 'info',
			sourcemap: false,
			treeShaking: true,
			outfile: 'main.js',
			minify: true,
			allowOverwrite: true,
		});
		console.log('✅ Build completed successfully!');
		console.log('📦 Output file: main.js');
	} catch (error) {
		console.error('❌ Build failed:', error);
		process.exit(1);
	}
}

build();
